# TP1

## Regresión

### Arquitectura

Se utiliza una red neuronal de tipo perceptrón multicapa con una capa de entrada de 7 neuronas, dos capas ocultas de 20 neuronas y una capa de salida de una neurona.

Se utilizará el optimizador de Keras *Adam* con una función de error *mean_squared_error* (error cuadrático medio), pasándole batches de 32 registros e iterando 300 veces el modelo para entrenarlo. La función de activación de las neuronas será por *unidad linear rectificada* excepto en la última capa, que será por *función linear (identidad)*

### Código

In [10]:
import os
import sys
# No mostrar WARNINGS
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from keras import backend as K
from keras.utils import to_categorical

import numpy as np

# Carga de datos en dataframe de pandas
raw = np.genfromtxt('Admission_Predict_Ver1.1.csv', delimiter=",")
raw = np.delete(raw, (0), axis=0)

print("Set de entrenamiento")
raw

Set de entrenamiento


array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [498.  , 330.  , 120.  , ...,   9.56,   1.  ,   0.93],
       [499.  , 312.  , 103.  , ...,   8.43,   0.  ,   0.73],
       [500.  , 327.  , 113.  , ...,   9.04,   0.  ,   0.84]])

In [11]:
# Se elimina la columna Serial No. y se divide set de entrenamiento y clases
X = raw[:,1:8]
Y = raw[:,8]

# Se normalizan los valores de las variables independientes
X = X / X.max(axis = 0)

print("Set de entrenamiento normalizado")
X

Set de entrenamiento normalizado


array([[0.99117647, 0.98333333, 0.8       , ..., 0.9       , 0.97278226,
        1.        ],
       [0.95294118, 0.89166667, 0.8       , ..., 0.9       , 0.89415323,
        1.        ],
       [0.92941176, 0.86666667, 0.6       , ..., 0.7       , 0.80645161,
        1.        ],
       ...,
       [0.97058824, 1.        , 1.        , ..., 1.        , 0.96370968,
        1.        ],
       [0.91764706, 0.85833333, 0.8       , ..., 1.        , 0.84979839,
        0.        ],
       [0.96176471, 0.94166667, 0.8       , ..., 0.9       , 0.91129032,
        0.        ]])

In [4]:
# Definición de arquitectura de la red
learning_rate = 0.001
n_layer_1 = 20
n_layer_2 = 20

def build_regression_model(train_set):
  model = keras.Sequential([
    layers.Dense(train_set.shape[1], activation=tf.nn.relu),
    layers.Dense(n_layer_1, activation=tf.nn.relu),
    layers.Dense(n_layer_2, activation=tf.nn.relu),
    layers.Dense(1, activation='linear')
  ])

  optimizer = tf.keras.optimizers.Adam(learning_rate)

  model.compile(loss='mean_squared_error',
                optimizer=optimizer)
  return model

In [12]:
# Definición de set de entrenamiento y validación
train_X, test_X, train_Y, test_Y = train_test_split(X, Y, test_size=0.33, random_state=42)

np.set_printoptions(threshold=sys.maxsize)

print("Casos de prueba")
print(train_X)
print("Casos de testeo")
print(test_X)

Casos de prueba
[[0.91470588 0.85833333 0.6        0.4        0.8        0.81552419
  0.        ]
 [0.94705882 0.90833333 1.         0.9        0.7        0.88709677
  0.        ]
 [0.90588235 0.84166667 0.4        0.6        0.8        0.79637097
  0.        ]
 [0.93823529 0.85833333 0.6        0.5        0.8        0.88306452
  1.        ]
 [0.97352941 0.96666667 1.         1.         1.         0.94556452
  1.        ]
 [0.88235294 0.875      0.2        0.2        0.4        0.78629032
  0.        ]
 [0.90882353 0.86666667 0.4        0.4        0.5        0.83266129
  0.        ]
 [0.88823529 0.91666667 0.6        0.8        0.9        0.85685484
  0.        ]
 [0.87058824 0.825      0.4        0.6        0.7        0.73387097
  0.        ]
 [0.91470588 0.875      0.6        0.7        0.6        0.85181452
  1.        ]
 [0.94117647 0.925      0.8        0.9        0.7        0.89415323
  1.        ]
 [0.94411765 0.90833333 0.6        0.6        0.6        0.8608871
  1.        ]
 

In [6]:
# Construcción de la red
model = build_regression_model(train_X)

# Entrenamiento
history = model.fit(train_X, train_Y, batch_size=32, epochs=300, verbose=1)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Use tf.cast instead.
Epoch 1/300
335/335 [==============================] - 1s 4ms/sample - loss: 0.0469
Epoch 2/300
335/335 [==============================] - 0s 132us/sample - loss: 0.0126
Epoch 3/300
335/335 [==============================] - 0s 127us/sample - loss: 0.0091
Epoch 4/300
335/335 [==============================] - 0s 133us/sample - loss: 0.0078
Epoch 5/300
335/335 [==============================] - 0s 142us/sample - loss: 0.0069
Epoch 6/300
335/335 [==============================] - 0s 122us/sample - loss: 0.0068
Epoch 7/300
335/335 [==============================] - 0s 122us/sample - loss: 0.0067
Epoch 8/300
335/335 [==============================] - 0s 131us/sample - loss: 0.0067
Epoch 9/300
335/335 [==============================] - 0s 131us/sample - loss: 0.0067
Epoch 10/300
335/335 [==============================] - 0s 1

Epoch 86/300
335/335 [==============================] - 0s 144us/sample - loss: 0.0056
Epoch 87/300
335/335 [==============================] - 0s 164us/sample - loss: 0.0058
Epoch 88/300
335/335 [==============================] - 0s 159us/sample - loss: 0.0055
Epoch 89/300
335/335 [==============================] - 0s 148us/sample - loss: 0.0056
Epoch 90/300
335/335 [==============================] - 0s 147us/sample - loss: 0.0056
Epoch 91/300
335/335 [==============================] - 0s 151us/sample - loss: 0.0056
Epoch 92/300
335/335 [==============================] - 0s 150us/sample - loss: 0.0055
Epoch 93/300
335/335 [==============================] - 0s 162us/sample - loss: 0.0055
Epoch 94/300
335/335 [==============================] - 0s 156us/sample - loss: 0.0055
Epoch 95/300
335/335 [==============================] - 0s 151us/sample - loss: 0.0055
Epoch 96/300
335/335 [==============================] - 0s 147us/sample - loss: 0.0056
Epoch 97/300
335/335 [=====================

335/335 [==============================] - 0s 143us/sample - loss: 0.0049
Epoch 180/300
335/335 [==============================] - 0s 164us/sample - loss: 0.0049
Epoch 181/300
335/335 [==============================] - 0s 141us/sample - loss: 0.0048
Epoch 182/300
335/335 [==============================] - 0s 133us/sample - loss: 0.0049
Epoch 183/300
335/335 [==============================] - 0s 114us/sample - loss: 0.0047
Epoch 184/300
335/335 [==============================] - 0s 128us/sample - loss: 0.0048
Epoch 185/300
335/335 [==============================] - 0s 114us/sample - loss: 0.0047
Epoch 186/300
335/335 [==============================] - 0s 131us/sample - loss: 0.0048
Epoch 187/300
335/335 [==============================] - 0s 113us/sample - loss: 0.0047
Epoch 188/300
335/335 [==============================] - 0s 147us/sample - loss: 0.0047
Epoch 189/300
335/335 [==============================] - 0s 143us/sample - loss: 0.0047
Epoch 190/300
335/335 [=======================

335/335 [==============================] - 0s 166us/sample - loss: 0.0048
Epoch 273/300
335/335 [==============================] - 0s 152us/sample - loss: 0.0048
Epoch 274/300
335/335 [==============================] - 0s 134us/sample - loss: 0.0044
Epoch 275/300
335/335 [==============================] - 0s 123us/sample - loss: 0.0045
Epoch 276/300
335/335 [==============================] - 0s 139us/sample - loss: 0.0045
Epoch 277/300
335/335 [==============================] - 0s 142us/sample - loss: 0.0044
Epoch 278/300
335/335 [==============================] - 0s 136us/sample - loss: 0.0044
Epoch 279/300
335/335 [==============================] - 0s 128us/sample - loss: 0.0043
Epoch 280/300
335/335 [==============================] - 0s 137us/sample - loss: 0.0046
Epoch 281/300
335/335 [==============================] - 0s 140us/sample - loss: 0.0046
Epoch 282/300
335/335 [==============================] - 0s 127us/sample - loss: 0.0045
Epoch 283/300
335/335 [=======================

In [7]:
# Predicción
predicted = model.predict(test_X)

def ecm(a, b):
  acc = 0
  for i in range(len(a)):
    acc = (a[i] - b[i])**2
  return acc / len(a)

# Cálculo de error cuadrático medio de la predicción respecto del resultado esperado
print("Error cuadrático medio:", ecm(predicted, test_Y))

Error cuadrático medio: [7.8394044e-07]


## Clasificación

### Arquitectura

Se utiliza una red neuronal de tipo perceptrón multicapa con una capa de entrada de 7 neuronas, tres capas ocultas de 68 neuronas y una capa de salida de cinco neuronas (una por cada clase).

Se utilizará el optimizador de Keras Adam con una función de error *categorical_crossentropy* (entropía cruzada categórica), pasándole batches de 32 registros e iterando 300 veces el modelo para entrenarlo. El umbral de activación de las neuronas será por *unidad linear rectificada* excepto en la última capa, que será por *función SoftMax*

### Código

In [13]:
def mapping(x):
  if (x <= 0.5):
    return [1,0,0,0,0];
  if (x <= 0.65):
    return [0,1,0,0,0];
  if (x <= 0.8):
    return  [0,0,1,0,0];
  if (x <= 0.9):
    return  [0,0,0,1,0];
  if (x <= 1):
    return  [0,0,0,0,1];

# Se agrupan los valores de la variable dependiente según requerimiento
Y = np.array(list(map(mapping, Y)))
print(Y)

[[0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]

In [92]:
# Definición de arquitectura
def build_classification_model(train_set):
  model = keras.Sequential([
    layers.Dense(68, input_dim=train_set.shape[1], activation=tf.nn.relu),
    layers.Dense(68, activation=tf.nn.relu),
    layers.Dense(5, activation=tf.nn.softmax)
  ])

  optimizer = tf.keras.optimizers.Adam(0.001)

  model.compile(loss='categorical_crossentropy',
                optimizer=optimizer,
                metrics=['accuracy', 'categorical_accuracy', 'mean_squared_error'])
  return model


In [16]:
# Se separa el set de datos en set de entrenamiento y de prueba
train_X, test_X, train_Y, test_Y = train_test_split(X, Y, test_size=0.33, random_state=42, stratify=Y)

print("Casos de prueba")
print(train_X)
print("Casos de testeo")
print(test_X)

Casos de prueba
[[0.93823529 0.88333333 0.6        0.7        0.5        0.83971774
  1.        ]
 [0.94411765 0.91666667 0.8        0.7        0.8        0.84173387
  1.        ]
 [0.89411765 0.875      0.2        0.6        0.3        0.75604839
  0.        ]
 [0.94705882 0.875      0.4        0.6        0.6        0.85181452
  1.        ]
 [0.92647059 0.875      0.6        0.4        0.5        0.84072581
  0.        ]
 [0.87352941 0.83333333 0.2        0.3        0.4        0.79637097
  0.        ]
 [0.95       0.94166667 0.8        0.8        0.9        0.93044355
  1.        ]
 [0.94705882 0.91666667 0.8        0.8        1.         0.9203629
  1.        ]
 [0.87941176 0.83333333 0.4        0.4        0.4        0.79435484
  0.        ]
 [0.85294118 0.83333333 0.2        0.3        0.4        0.76209677
  0.        ]
 [0.92941176 0.86666667 0.6        0.6        0.7        0.80645161
  1.        ]
 [0.90588235 0.90833333 0.4        0.6        0.8        0.85181452
  0.        ]
 

In [93]:
# Construcción de la red
model = build_classification_model(train_X)

# Entrenamiento
history = model.fit(train_X, train_Y, batch_size=32, epochs=1000, verbose=1)

# Predicción
scores = model.evaluate(test_X, test_Y)
print("\nCasos de éxito: %.2f%%" % (scores[1]*100))

Epoch 1/1000
335/335 [==============================] - 2s 6ms/sample - loss: 1.5351 - acc: 0.3493 - categorical_accuracy: 0.3493 - mean_squared_error: 0.1540
Epoch 2/1000
335/335 [==============================] - 0s 235us/sample - loss: 1.4532 - acc: 0.4000 - categorical_accuracy: 0.4000 - mean_squared_error: 0.1471
Epoch 3/1000
335/335 [==============================] - 0s 237us/sample - loss: 1.4171 - acc: 0.4000 - categorical_accuracy: 0.4000 - mean_squared_error: 0.1446
Epoch 4/1000
335/335 [==============================] - 0s 236us/sample - loss: 1.3938 - acc: 0.4209 - categorical_accuracy: 0.4209 - mean_squared_error: 0.1430
Epoch 5/1000
335/335 [==============================] - 0s 236us/sample - loss: 1.3660 - acc: 0.4328 - categorical_accuracy: 0.4328 - mean_squared_error: 0.1408
Epoch 6/1000
335/335 [==============================] - 0s 232us/sample - loss: 1.3408 - acc: 0.4478 - categorical_accuracy: 0.4478 - mean_squared_error: 0.1390
Epoch 7/1000
335/335 [==============

335/335 [==============================] - 0s 237us/sample - loss: 0.9830 - acc: 0.5612 - categorical_accuracy: 0.5612 - mean_squared_error: 0.1123
Epoch 52/1000
335/335 [==============================] - 0s 233us/sample - loss: 0.9743 - acc: 0.5672 - categorical_accuracy: 0.5672 - mean_squared_error: 0.1112
Epoch 53/1000
335/335 [==============================] - 0s 231us/sample - loss: 0.9728 - acc: 0.5731 - categorical_accuracy: 0.5731 - mean_squared_error: 0.1114
Epoch 54/1000
335/335 [==============================] - 0s 240us/sample - loss: 0.9678 - acc: 0.5672 - categorical_accuracy: 0.5672 - mean_squared_error: 0.1106
Epoch 55/1000
335/335 [==============================] - 0s 230us/sample - loss: 0.9651 - acc: 0.5761 - categorical_accuracy: 0.5761 - mean_squared_error: 0.1104
Epoch 56/1000
335/335 [==============================] - 0s 239us/sample - loss: 0.9676 - acc: 0.5791 - categorical_accuracy: 0.5791 - mean_squared_error: 0.1107
Epoch 57/1000
335/335 [===================

335/335 [==============================] - 0s 239us/sample - loss: 0.9365 - acc: 0.5910 - categorical_accuracy: 0.5910 - mean_squared_error: 0.1084
Epoch 102/1000
335/335 [==============================] - 0s 231us/sample - loss: 0.9336 - acc: 0.5821 - categorical_accuracy: 0.5821 - mean_squared_error: 0.1077
Epoch 103/1000
335/335 [==============================] - 0s 235us/sample - loss: 0.9348 - acc: 0.5881 - categorical_accuracy: 0.5881 - mean_squared_error: 0.1081
Epoch 104/1000
335/335 [==============================] - 0s 234us/sample - loss: 0.9335 - acc: 0.5881 - categorical_accuracy: 0.5881 - mean_squared_error: 0.1075
Epoch 105/1000
335/335 [==============================] - 0s 235us/sample - loss: 0.9319 - acc: 0.5940 - categorical_accuracy: 0.5940 - mean_squared_error: 0.1075
Epoch 106/1000
335/335 [==============================] - 0s 247us/sample - loss: 0.9350 - acc: 0.5821 - categorical_accuracy: 0.5821 - mean_squared_error: 0.1080
Epoch 107/1000
335/335 [=============

335/335 [==============================] - 0s 237us/sample - loss: 0.9073 - acc: 0.5910 - categorical_accuracy: 0.5910 - mean_squared_error: 0.1054
Epoch 152/1000
335/335 [==============================] - 0s 235us/sample - loss: 0.9063 - acc: 0.5970 - categorical_accuracy: 0.5970 - mean_squared_error: 0.1051
Epoch 153/1000
335/335 [==============================] - 0s 236us/sample - loss: 0.9108 - acc: 0.5851 - categorical_accuracy: 0.5851 - mean_squared_error: 0.1054
Epoch 154/1000
335/335 [==============================] - 0s 245us/sample - loss: 0.9165 - acc: 0.5851 - categorical_accuracy: 0.5851 - mean_squared_error: 0.1062
Epoch 155/1000
335/335 [==============================] - 0s 231us/sample - loss: 0.9045 - acc: 0.5851 - categorical_accuracy: 0.5851 - mean_squared_error: 0.1051
Epoch 156/1000
335/335 [==============================] - 0s 232us/sample - loss: 0.9120 - acc: 0.5970 - categorical_accuracy: 0.5970 - mean_squared_error: 0.1058
Epoch 157/1000
335/335 [=============

335/335 [==============================] - 0s 234us/sample - loss: 0.8825 - acc: 0.5940 - categorical_accuracy: 0.5940 - mean_squared_error: 0.1035
Epoch 202/1000
335/335 [==============================] - 0s 242us/sample - loss: 0.8848 - acc: 0.6060 - categorical_accuracy: 0.6060 - mean_squared_error: 0.1033
Epoch 203/1000
335/335 [==============================] - 0s 229us/sample - loss: 0.8786 - acc: 0.6000 - categorical_accuracy: 0.6000 - mean_squared_error: 0.1024
Epoch 204/1000
335/335 [==============================] - 0s 231us/sample - loss: 0.8948 - acc: 0.5761 - categorical_accuracy: 0.5761 - mean_squared_error: 0.1047
Epoch 205/1000
335/335 [==============================] - 0s 247us/sample - loss: 0.8865 - acc: 0.5970 - categorical_accuracy: 0.5970 - mean_squared_error: 0.1033
Epoch 206/1000
335/335 [==============================] - 0s 231us/sample - loss: 0.8794 - acc: 0.6090 - categorical_accuracy: 0.6090 - mean_squared_error: 0.1027
Epoch 207/1000
335/335 [=============

335/335 [==============================] - 0s 299us/sample - loss: 0.8586 - acc: 0.6119 - categorical_accuracy: 0.6119 - mean_squared_error: 0.1005
Epoch 252/1000
335/335 [==============================] - 0s 247us/sample - loss: 0.8445 - acc: 0.6269 - categorical_accuracy: 0.6269 - mean_squared_error: 0.0993
Epoch 253/1000
335/335 [==============================] - 0s 353us/sample - loss: 0.8398 - acc: 0.6299 - categorical_accuracy: 0.6299 - mean_squared_error: 0.0984
Epoch 254/1000
335/335 [==============================] - 0s 355us/sample - loss: 0.8378 - acc: 0.6358 - categorical_accuracy: 0.6358 - mean_squared_error: 0.0982
Epoch 255/1000
335/335 [==============================] - 0s 271us/sample - loss: 0.8417 - acc: 0.6149 - categorical_accuracy: 0.6149 - mean_squared_error: 0.0993
Epoch 256/1000
335/335 [==============================] - 0s 260us/sample - loss: 0.8423 - acc: 0.6149 - categorical_accuracy: 0.6149 - mean_squared_error: 0.0994
Epoch 257/1000
335/335 [=============

335/335 [==============================] - 0s 245us/sample - loss: 0.8019 - acc: 0.6537 - categorical_accuracy: 0.6537 - mean_squared_error: 0.0946
Epoch 302/1000
335/335 [==============================] - 0s 232us/sample - loss: 0.8019 - acc: 0.6418 - categorical_accuracy: 0.6418 - mean_squared_error: 0.0950
Epoch 303/1000
335/335 [==============================] - 0s 231us/sample - loss: 0.7969 - acc: 0.6478 - categorical_accuracy: 0.6478 - mean_squared_error: 0.0944
Epoch 304/1000
335/335 [==============================] - 0s 264us/sample - loss: 0.7917 - acc: 0.6537 - categorical_accuracy: 0.6537 - mean_squared_error: 0.0937
Epoch 305/1000
335/335 [==============================] - 0s 303us/sample - loss: 0.7991 - acc: 0.6328 - categorical_accuracy: 0.6328 - mean_squared_error: 0.0947
Epoch 306/1000
335/335 [==============================] - 0s 278us/sample - loss: 0.7946 - acc: 0.6537 - categorical_accuracy: 0.6537 - mean_squared_error: 0.0938
Epoch 307/1000
335/335 [=============

335/335 [==============================] - 0s 315us/sample - loss: 0.7582 - acc: 0.6687 - categorical_accuracy: 0.6687 - mean_squared_error: 0.0894
Epoch 352/1000
335/335 [==============================] - 0s 319us/sample - loss: 0.7520 - acc: 0.6537 - categorical_accuracy: 0.6537 - mean_squared_error: 0.0897
Epoch 353/1000
335/335 [==============================] - 0s 287us/sample - loss: 0.7490 - acc: 0.6806 - categorical_accuracy: 0.6806 - mean_squared_error: 0.0890
Epoch 354/1000
335/335 [==============================] - 0s 236us/sample - loss: 0.7607 - acc: 0.6746 - categorical_accuracy: 0.6746 - mean_squared_error: 0.0902
Epoch 355/1000
335/335 [==============================] - 0s 261us/sample - loss: 0.7541 - acc: 0.6597 - categorical_accuracy: 0.6597 - mean_squared_error: 0.0898
Epoch 356/1000
335/335 [==============================] - 0s 266us/sample - loss: 0.7493 - acc: 0.6627 - categorical_accuracy: 0.6627 - mean_squared_error: 0.0890
Epoch 357/1000
335/335 [=============

335/335 [==============================] - 0s 275us/sample - loss: 0.7127 - acc: 0.6955 - categorical_accuracy: 0.6955 - mean_squared_error: 0.0847
Epoch 402/1000
335/335 [==============================] - 0s 269us/sample - loss: 0.7024 - acc: 0.6985 - categorical_accuracy: 0.6985 - mean_squared_error: 0.0836
Epoch 403/1000
335/335 [==============================] - 0s 452us/sample - loss: 0.7167 - acc: 0.6836 - categorical_accuracy: 0.6836 - mean_squared_error: 0.0859
Epoch 404/1000
335/335 [==============================] - 0s 254us/sample - loss: 0.7149 - acc: 0.6955 - categorical_accuracy: 0.6955 - mean_squared_error: 0.0853
Epoch 405/1000
335/335 [==============================] - 0s 250us/sample - loss: 0.7055 - acc: 0.6806 - categorical_accuracy: 0.6806 - mean_squared_error: 0.0846
Epoch 406/1000
335/335 [==============================] - 0s 267us/sample - loss: 0.7133 - acc: 0.7015 - categorical_accuracy: 0.7015 - mean_squared_error: 0.0852
Epoch 407/1000
335/335 [=============

335/335 [==============================] - 0s 266us/sample - loss: 0.6920 - acc: 0.6896 - categorical_accuracy: 0.6896 - mean_squared_error: 0.0834
Epoch 452/1000
335/335 [==============================] - 0s 264us/sample - loss: 0.6929 - acc: 0.6955 - categorical_accuracy: 0.6955 - mean_squared_error: 0.0833
Epoch 453/1000
335/335 [==============================] - 0s 260us/sample - loss: 0.6951 - acc: 0.6896 - categorical_accuracy: 0.6896 - mean_squared_error: 0.0837
Epoch 454/1000
335/335 [==============================] - 0s 263us/sample - loss: 0.6812 - acc: 0.6985 - categorical_accuracy: 0.6985 - mean_squared_error: 0.0818
Epoch 455/1000
335/335 [==============================] - 0s 276us/sample - loss: 0.6763 - acc: 0.7015 - categorical_accuracy: 0.7015 - mean_squared_error: 0.0808
Epoch 456/1000
335/335 [==============================] - 0s 260us/sample - loss: 0.6890 - acc: 0.7045 - categorical_accuracy: 0.7045 - mean_squared_error: 0.0831
Epoch 457/1000
335/335 [=============

335/335 [==============================] - 0s 262us/sample - loss: 0.6900 - acc: 0.6657 - categorical_accuracy: 0.6657 - mean_squared_error: 0.0840
Epoch 502/1000
335/335 [==============================] - 0s 289us/sample - loss: 0.6802 - acc: 0.6866 - categorical_accuracy: 0.6866 - mean_squared_error: 0.0823
Epoch 503/1000
335/335 [==============================] - 0s 371us/sample - loss: 0.6602 - acc: 0.7045 - categorical_accuracy: 0.7045 - mean_squared_error: 0.0792
Epoch 504/1000
335/335 [==============================] - 0s 263us/sample - loss: 0.6838 - acc: 0.7134 - categorical_accuracy: 0.7134 - mean_squared_error: 0.0820
Epoch 505/1000
335/335 [==============================] - 0s 233us/sample - loss: 0.6768 - acc: 0.7045 - categorical_accuracy: 0.7045 - mean_squared_error: 0.0814
Epoch 506/1000
335/335 [==============================] - 0s 234us/sample - loss: 0.6532 - acc: 0.7134 - categorical_accuracy: 0.7134 - mean_squared_error: 0.0780
Epoch 507/1000
335/335 [=============

335/335 [==============================] - 0s 239us/sample - loss: 0.6491 - acc: 0.7493 - categorical_accuracy: 0.7493 - mean_squared_error: 0.0777
Epoch 551/1000
335/335 [==============================] - 0s 237us/sample - loss: 0.6537 - acc: 0.7164 - categorical_accuracy: 0.7164 - mean_squared_error: 0.0788
Epoch 552/1000
335/335 [==============================] - 0s 249us/sample - loss: 0.6490 - acc: 0.7343 - categorical_accuracy: 0.7343 - mean_squared_error: 0.0778
Epoch 553/1000
335/335 [==============================] - 0s 379us/sample - loss: 0.6399 - acc: 0.7403 - categorical_accuracy: 0.7403 - mean_squared_error: 0.0767
Epoch 554/1000
335/335 [==============================] - 0s 277us/sample - loss: 0.6531 - acc: 0.7104 - categorical_accuracy: 0.7104 - mean_squared_error: 0.0790
Epoch 555/1000
335/335 [==============================] - 0s 254us/sample - loss: 0.6798 - acc: 0.6806 - categorical_accuracy: 0.6806 - mean_squared_error: 0.0822
Epoch 556/1000
335/335 [=============

335/335 [==============================] - 0s 240us/sample - loss: 0.6325 - acc: 0.7403 - categorical_accuracy: 0.7403 - mean_squared_error: 0.0758
Epoch 601/1000
335/335 [==============================] - 0s 230us/sample - loss: 0.6537 - acc: 0.7045 - categorical_accuracy: 0.7045 - mean_squared_error: 0.0786
Epoch 602/1000
335/335 [==============================] - 0s 233us/sample - loss: 0.6756 - acc: 0.7254 - categorical_accuracy: 0.7254 - mean_squared_error: 0.0810
Epoch 603/1000
335/335 [==============================] - 0s 238us/sample - loss: 0.6372 - acc: 0.7403 - categorical_accuracy: 0.7403 - mean_squared_error: 0.0767
Epoch 604/1000
335/335 [==============================] - 0s 234us/sample - loss: 0.6371 - acc: 0.7224 - categorical_accuracy: 0.7224 - mean_squared_error: 0.0766
Epoch 605/1000
335/335 [==============================] - 0s 237us/sample - loss: 0.6468 - acc: 0.7254 - categorical_accuracy: 0.7254 - mean_squared_error: 0.0777
Epoch 606/1000
335/335 [=============

335/335 [==============================] - 0s 245us/sample - loss: 0.6407 - acc: 0.7194 - categorical_accuracy: 0.7194 - mean_squared_error: 0.0774
Epoch 651/1000
335/335 [==============================] - 0s 241us/sample - loss: 0.6328 - acc: 0.7015 - categorical_accuracy: 0.7015 - mean_squared_error: 0.0767
Epoch 652/1000
335/335 [==============================] - 0s 237us/sample - loss: 0.6213 - acc: 0.7403 - categorical_accuracy: 0.7403 - mean_squared_error: 0.0746
Epoch 653/1000
335/335 [==============================] - 0s 232us/sample - loss: 0.6196 - acc: 0.7493 - categorical_accuracy: 0.7493 - mean_squared_error: 0.0746
Epoch 654/1000
335/335 [==============================] - 0s 239us/sample - loss: 0.6226 - acc: 0.7463 - categorical_accuracy: 0.7463 - mean_squared_error: 0.0744
Epoch 655/1000
335/335 [==============================] - 0s 234us/sample - loss: 0.6185 - acc: 0.7313 - categorical_accuracy: 0.7313 - mean_squared_error: 0.0743
Epoch 656/1000
335/335 [=============

335/335 [==============================] - 0s 236us/sample - loss: 0.6693 - acc: 0.7194 - categorical_accuracy: 0.7194 - mean_squared_error: 0.0813
Epoch 701/1000
335/335 [==============================] - 0s 237us/sample - loss: 0.6104 - acc: 0.7463 - categorical_accuracy: 0.7463 - mean_squared_error: 0.0732
Epoch 702/1000
335/335 [==============================] - 0s 317us/sample - loss: 0.6276 - acc: 0.7343 - categorical_accuracy: 0.7343 - mean_squared_error: 0.0762
Epoch 703/1000
335/335 [==============================] - 0s 306us/sample - loss: 0.6212 - acc: 0.7493 - categorical_accuracy: 0.7493 - mean_squared_error: 0.0749
Epoch 704/1000
335/335 [==============================] - 0s 288us/sample - loss: 0.6127 - acc: 0.7552 - categorical_accuracy: 0.7552 - mean_squared_error: 0.0729
Epoch 705/1000
335/335 [==============================] - 0s 238us/sample - loss: 0.6177 - acc: 0.7403 - categorical_accuracy: 0.7403 - mean_squared_error: 0.0741
Epoch 706/1000
335/335 [=============

335/335 [==============================] - 0s 237us/sample - loss: 0.6096 - acc: 0.7373 - categorical_accuracy: 0.7373 - mean_squared_error: 0.0729
Epoch 751/1000
335/335 [==============================] - 0s 239us/sample - loss: 0.6125 - acc: 0.7463 - categorical_accuracy: 0.7463 - mean_squared_error: 0.0735
Epoch 752/1000
335/335 [==============================] - 0s 233us/sample - loss: 0.6050 - acc: 0.7463 - categorical_accuracy: 0.7463 - mean_squared_error: 0.0729
Epoch 753/1000
335/335 [==============================] - 0s 234us/sample - loss: 0.6058 - acc: 0.7463 - categorical_accuracy: 0.7463 - mean_squared_error: 0.0729
Epoch 754/1000
335/335 [==============================] - 0s 236us/sample - loss: 0.6119 - acc: 0.7373 - categorical_accuracy: 0.7373 - mean_squared_error: 0.0735
Epoch 755/1000
335/335 [==============================] - 0s 237us/sample - loss: 0.6028 - acc: 0.7463 - categorical_accuracy: 0.7463 - mean_squared_error: 0.0721
Epoch 756/1000
335/335 [=============

335/335 [==============================] - 0s 241us/sample - loss: 0.6024 - acc: 0.7582 - categorical_accuracy: 0.7582 - mean_squared_error: 0.0713
Epoch 801/1000
335/335 [==============================] - 0s 240us/sample - loss: 0.6087 - acc: 0.7403 - categorical_accuracy: 0.7403 - mean_squared_error: 0.0735
Epoch 802/1000
335/335 [==============================] - 0s 237us/sample - loss: 0.5942 - acc: 0.7463 - categorical_accuracy: 0.7463 - mean_squared_error: 0.0716
Epoch 803/1000
335/335 [==============================] - 0s 244us/sample - loss: 0.6039 - acc: 0.7403 - categorical_accuracy: 0.7403 - mean_squared_error: 0.0727
Epoch 804/1000
335/335 [==============================] - 0s 235us/sample - loss: 0.6022 - acc: 0.7313 - categorical_accuracy: 0.7313 - mean_squared_error: 0.0724
Epoch 805/1000
335/335 [==============================] - 0s 234us/sample - loss: 0.6022 - acc: 0.7403 - categorical_accuracy: 0.7403 - mean_squared_error: 0.0717
Epoch 806/1000
335/335 [=============

335/335 [==============================] - 0s 241us/sample - loss: 0.6226 - acc: 0.7194 - categorical_accuracy: 0.7194 - mean_squared_error: 0.0752
Epoch 850/1000
335/335 [==============================] - 0s 236us/sample - loss: 0.6085 - acc: 0.7313 - categorical_accuracy: 0.7313 - mean_squared_error: 0.0739
Epoch 851/1000
335/335 [==============================] - 0s 237us/sample - loss: 0.6066 - acc: 0.7433 - categorical_accuracy: 0.7433 - mean_squared_error: 0.0730
Epoch 852/1000
335/335 [==============================] - 0s 240us/sample - loss: 0.5991 - acc: 0.7433 - categorical_accuracy: 0.7433 - mean_squared_error: 0.0722
Epoch 853/1000
335/335 [==============================] - 0s 255us/sample - loss: 0.5951 - acc: 0.7493 - categorical_accuracy: 0.7493 - mean_squared_error: 0.0714
Epoch 854/1000
335/335 [==============================] - 0s 273us/sample - loss: 0.5934 - acc: 0.7493 - categorical_accuracy: 0.7493 - mean_squared_error: 0.0712
Epoch 855/1000
335/335 [=============

335/335 [==============================] - 0s 230us/sample - loss: 0.6078 - acc: 0.7194 - categorical_accuracy: 0.7194 - mean_squared_error: 0.0730
Epoch 900/1000
335/335 [==============================] - 0s 233us/sample - loss: 0.6505 - acc: 0.7015 - categorical_accuracy: 0.7015 - mean_squared_error: 0.0784
Epoch 901/1000
335/335 [==============================] - 0s 251us/sample - loss: 0.5855 - acc: 0.7612 - categorical_accuracy: 0.7612 - mean_squared_error: 0.0700
Epoch 902/1000
335/335 [==============================] - 0s 240us/sample - loss: 0.6014 - acc: 0.7463 - categorical_accuracy: 0.7463 - mean_squared_error: 0.0727
Epoch 903/1000
335/335 [==============================] - 0s 236us/sample - loss: 0.6375 - acc: 0.7045 - categorical_accuracy: 0.7045 - mean_squared_error: 0.0775
Epoch 904/1000
335/335 [==============================] - 0s 235us/sample - loss: 0.5978 - acc: 0.7224 - categorical_accuracy: 0.7224 - mean_squared_error: 0.0730
Epoch 905/1000
335/335 [=============

335/335 [==============================] - 0s 244us/sample - loss: 0.5996 - acc: 0.7433 - categorical_accuracy: 0.7433 - mean_squared_error: 0.0718
Epoch 950/1000
335/335 [==============================] - 0s 233us/sample - loss: 0.6282 - acc: 0.7075 - categorical_accuracy: 0.7075 - mean_squared_error: 0.0764
Epoch 951/1000
335/335 [==============================] - 0s 233us/sample - loss: 0.6081 - acc: 0.7343 - categorical_accuracy: 0.7343 - mean_squared_error: 0.0729
Epoch 952/1000
335/335 [==============================] - 0s 234us/sample - loss: 0.6077 - acc: 0.7284 - categorical_accuracy: 0.7284 - mean_squared_error: 0.0731
Epoch 953/1000
335/335 [==============================] - 0s 237us/sample - loss: 0.6102 - acc: 0.7254 - categorical_accuracy: 0.7254 - mean_squared_error: 0.0739
Epoch 954/1000
335/335 [==============================] - 0s 239us/sample - loss: 0.6298 - acc: 0.7015 - categorical_accuracy: 0.7015 - mean_squared_error: 0.0771
Epoch 955/1000
335/335 [=============

335/335 [==============================] - 0s 231us/sample - loss: 0.5761 - acc: 0.7612 - categorical_accuracy: 0.7612 - mean_squared_error: 0.0691
Epoch 1000/1000
165/165 [==============================] - 2s 10ms/sample - loss: 0.6923 - acc: 0.7212 - categorical_accuracy: 0.7212 - mean_squared_error: 0.0835

Casos de éxito: 72.12%
