# TP01: *Redes Neuronales*

**Grupo 01**

**Alumno**: *Bruno Liberini*, 90899

## Regresión

### Arquitectura

Se utiliza una red neuronal de tipo perceptrón multicapa con una capa de entrada de 7 neuronas, dos capas ocultas de 20 neuronas y una capa de salida de una neurona.

Se utilizará el optimizador de Keras *Adam* con una función de error *mean_squared_error* (error cuadrático medio), pasándole batches de 32 registros e iterando 300 veces el modelo para entrenarlo. La función de activación de las neuronas será por *unidad linear rectificada* excepto en la última capa, que será por *función linear (identidad)*

### Carga de datos y codificación de modelo

In [10]:
import os
import sys
# No mostrar WARNINGS
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from keras import backend as K
from keras.utils import to_categorical

import numpy as np

# Carga de datos en dataframe de pandas
raw = np.genfromtxt('Admission_Predict_Ver1.1.csv', delimiter=",")
raw = np.delete(raw, (0), axis=0)

print("Set de entrenamiento")
raw

Set de entrenamiento


array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [498.  , 330.  , 120.  , ...,   9.56,   1.  ,   0.93],
       [499.  , 312.  , 103.  , ...,   8.43,   0.  ,   0.73],
       [500.  , 327.  , 113.  , ...,   9.04,   0.  ,   0.84]])

In [11]:
# Se elimina la columna Serial No. y se divide set de entrenamiento y clases
X = raw[:,1:8]
Y = raw[:,8]

# Se normalizan los valores de las variables independientes
X = X / X.max(axis = 0)

print("Set de entrenamiento normalizado")
X

Set de entrenamiento normalizado


array([[0.99117647, 0.98333333, 0.8       , ..., 0.9       , 0.97278226,
        1.        ],
       [0.95294118, 0.89166667, 0.8       , ..., 0.9       , 0.89415323,
        1.        ],
       [0.92941176, 0.86666667, 0.6       , ..., 0.7       , 0.80645161,
        1.        ],
       ...,
       [0.97058824, 1.        , 1.        , ..., 1.        , 0.96370968,
        1.        ],
       [0.91764706, 0.85833333, 0.8       , ..., 1.        , 0.84979839,
        0.        ],
       [0.96176471, 0.94166667, 0.8       , ..., 0.9       , 0.91129032,
        0.        ]])

In [4]:
# Definición de arquitectura de la red
learning_rate = 0.001
n_layer_1 = 20
n_layer_2 = 20

def build_regression_model(train_set):
  model = keras.Sequential([
    layers.Dense(train_set.shape[1], activation=tf.nn.relu),
    layers.Dense(n_layer_1, activation=tf.nn.relu),
    layers.Dense(n_layer_2, activation=tf.nn.relu),
    layers.Dense(1, activation='linear')
  ])

  optimizer = tf.keras.optimizers.Adam(learning_rate)

  model.compile(loss='mean_squared_error',
                optimizer=optimizer)
  return model

### Set de entrenamiento y set de prueba

In [12]:
# Definición de set de entrenamiento y validación
train_X, test_X, train_Y, test_Y = train_test_split(X, Y, test_size=0.33, random_state=42)

np.set_printoptions(threshold=sys.maxsize)

print("Casos de prueba")
print(train_X)
print("Casos de testeo")
print(test_X)

Casos de prueba
[[0.91470588 0.85833333 0.6        0.4        0.8        0.81552419
  0.        ]
 [0.94705882 0.90833333 1.         0.9        0.7        0.88709677
  0.        ]
 [0.90588235 0.84166667 0.4        0.6        0.8        0.79637097
  0.        ]
 [0.93823529 0.85833333 0.6        0.5        0.8        0.88306452
  1.        ]
 [0.97352941 0.96666667 1.         1.         1.         0.94556452
  1.        ]
 [0.88235294 0.875      0.2        0.2        0.4        0.78629032
  0.        ]
 [0.90882353 0.86666667 0.4        0.4        0.5        0.83266129
  0.        ]
 [0.88823529 0.91666667 0.6        0.8        0.9        0.85685484
  0.        ]
 [0.87058824 0.825      0.4        0.6        0.7        0.73387097
  0.        ]
 [0.91470588 0.875      0.6        0.7        0.6        0.85181452
  1.        ]
 [0.94117647 0.925      0.8        0.9        0.7        0.89415323
  1.        ]
 [0.94411765 0.90833333 0.6        0.6        0.6        0.8608871
  1.        ]
 

### Entrenamiento

In [6]:
# Construcción de la red
model = build_regression_model(train_X)

# Entrenamiento
history = model.fit(train_X, train_Y, batch_size=32, epochs=300, verbose=1)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Use tf.cast instead.
Epoch 1/300
335/335 [==============================] - 1s 4ms/sample - loss: 0.0469
Epoch 2/300
335/335 [==============================] - 0s 132us/sample - loss: 0.0126
Epoch 3/300
335/335 [==============================] - 0s 127us/sample - loss: 0.0091
Epoch 4/300
335/335 [==============================] - 0s 133us/sample - loss: 0.0078
Epoch 5/300
335/335 [==============================] - 0s 142us/sample - loss: 0.0069
Epoch 6/300
335/335 [==============================] - 0s 122us/sample - loss: 0.0068
Epoch 7/300
335/335 [==============================] - 0s 122us/sample - loss: 0.0067
Epoch 8/300
335/335 [==============================] - 0s 131us/sample - loss: 0.0067
Epoch 9/300
335/335 [==============================] - 0s 131us/sample - loss: 0.0067
Epoch 10/300
335/335 [==============================] - 0s 1

Epoch 86/300
335/335 [==============================] - 0s 144us/sample - loss: 0.0056
Epoch 87/300
335/335 [==============================] - 0s 164us/sample - loss: 0.0058
Epoch 88/300
335/335 [==============================] - 0s 159us/sample - loss: 0.0055
Epoch 89/300
335/335 [==============================] - 0s 148us/sample - loss: 0.0056
Epoch 90/300
335/335 [==============================] - 0s 147us/sample - loss: 0.0056
Epoch 91/300
335/335 [==============================] - 0s 151us/sample - loss: 0.0056
Epoch 92/300
335/335 [==============================] - 0s 150us/sample - loss: 0.0055
Epoch 93/300
335/335 [==============================] - 0s 162us/sample - loss: 0.0055
Epoch 94/300
335/335 [==============================] - 0s 156us/sample - loss: 0.0055
Epoch 95/300
335/335 [==============================] - 0s 151us/sample - loss: 0.0055
Epoch 96/300
335/335 [==============================] - 0s 147us/sample - loss: 0.0056
Epoch 97/300
335/335 [=====================

335/335 [==============================] - 0s 143us/sample - loss: 0.0049
Epoch 180/300
335/335 [==============================] - 0s 164us/sample - loss: 0.0049
Epoch 181/300
335/335 [==============================] - 0s 141us/sample - loss: 0.0048
Epoch 182/300
335/335 [==============================] - 0s 133us/sample - loss: 0.0049
Epoch 183/300
335/335 [==============================] - 0s 114us/sample - loss: 0.0047
Epoch 184/300
335/335 [==============================] - 0s 128us/sample - loss: 0.0048
Epoch 185/300
335/335 [==============================] - 0s 114us/sample - loss: 0.0047
Epoch 186/300
335/335 [==============================] - 0s 131us/sample - loss: 0.0048
Epoch 187/300
335/335 [==============================] - 0s 113us/sample - loss: 0.0047
Epoch 188/300
335/335 [==============================] - 0s 147us/sample - loss: 0.0047
Epoch 189/300
335/335 [==============================] - 0s 143us/sample - loss: 0.0047
Epoch 190/300
335/335 [=======================

335/335 [==============================] - 0s 166us/sample - loss: 0.0048
Epoch 273/300
335/335 [==============================] - 0s 152us/sample - loss: 0.0048
Epoch 274/300
335/335 [==============================] - 0s 134us/sample - loss: 0.0044
Epoch 275/300
335/335 [==============================] - 0s 123us/sample - loss: 0.0045
Epoch 276/300
335/335 [==============================] - 0s 139us/sample - loss: 0.0045
Epoch 277/300
335/335 [==============================] - 0s 142us/sample - loss: 0.0044
Epoch 278/300
335/335 [==============================] - 0s 136us/sample - loss: 0.0044
Epoch 279/300
335/335 [==============================] - 0s 128us/sample - loss: 0.0043
Epoch 280/300
335/335 [==============================] - 0s 137us/sample - loss: 0.0046
Epoch 281/300
335/335 [==============================] - 0s 140us/sample - loss: 0.0046
Epoch 282/300
335/335 [==============================] - 0s 127us/sample - loss: 0.0045
Epoch 283/300
335/335 [=======================

In [ ]:
### Validación

Se valida

In [7]:
# Predicción
predicted = model.predict(test_X)

def ecm(a, b):
  acc = 0
  for i in range(len(a)):
    acc = (a[i] - b[i])**2
  return acc / len(a)

# Cálculo de error cuadrático medio de la predicción respecto del resultado esperado
print("Error cuadrático medio:", ecm(predicted, test_Y))

Error cuadrático medio: [7.8394044e-07]


## Clasificación

### Arquitectura

Se utiliza una red neuronal de tipo perceptrón multicapa con una capa de entrada de 7 neuronas, tres capas ocultas de 68 neuronas y una capa de salida de cinco neuronas (una por cada clase).

Se utilizará el optimizador de Keras Adam con una función de error *categorical_crossentropy* (entropía cruzada categórica), pasándole batches de 32 registros e iterando 300 veces el modelo para entrenarlo. El umbral de activación de las neuronas será por *unidad linear rectificada* excepto en la última capa, que será por *función SoftMax*

### Carga de datos y codificación de modelo

In [13]:
def mapping(x):
  if (x <= 0.5):
    return [1,0,0,0,0];
  if (x <= 0.65):
    return [0,1,0,0,0];
  if (x <= 0.8):
    return  [0,0,1,0,0];
  if (x <= 0.9):
    return  [0,0,0,1,0];
  if (x <= 1):
    return  [0,0,0,0,1];

# Se agrupan los valores de la variable dependiente según requerimiento
Y = np.array(list(map(mapping, Y)))
print(Y)

[[0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]

In [92]:
# Definición de arquitectura
def build_classification_model(train_set):
  model = keras.Sequential([
    layers.Dense(68, input_dim=train_set.shape[1], activation=tf.nn.relu),
    layers.Dense(68, activation=tf.nn.relu),
    layers.Dense(5, activation=tf.nn.softmax)
  ])

  optimizer = tf.keras.optimizers.Adam(0.001)

  model.compile(loss='categorical_crossentropy',
                optimizer=optimizer,
                metrics=['accuracy', 'categorical_accuracy', 'mean_squared_error'])
  return model


### Set de entrenamiento y set de prueba

In [16]:
# Se separa el set de datos en set de entrenamiento y de prueba
train_X, test_X, train_Y, test_Y = train_test_split(X, Y, test_size=0.33, random_state=42, stratify=Y)

print("Casos de prueba")
print(train_X)
print("Casos de testeo")
print(test_X)

Casos de prueba
[[0.93823529 0.88333333 0.6        0.7        0.5        0.83971774
  1.        ]
 [0.94411765 0.91666667 0.8        0.7        0.8        0.84173387
  1.        ]
 [0.89411765 0.875      0.2        0.6        0.3        0.75604839
  0.        ]
 [0.94705882 0.875      0.4        0.6        0.6        0.85181452
  1.        ]
 [0.92647059 0.875      0.6        0.4        0.5        0.84072581
  0.        ]
 [0.87352941 0.83333333 0.2        0.3        0.4        0.79637097
  0.        ]
 [0.95       0.94166667 0.8        0.8        0.9        0.93044355
  1.        ]
 [0.94705882 0.91666667 0.8        0.8        1.         0.9203629
  1.        ]
 [0.87941176 0.83333333 0.4        0.4        0.4        0.79435484
  0.        ]
 [0.85294118 0.83333333 0.2        0.3        0.4        0.76209677
  0.        ]
 [0.92941176 0.86666667 0.6        0.6        0.7        0.80645161
  1.        ]
 [0.90588235 0.90833333 0.4        0.6        0.8        0.85181452
  0.        ]
 

### Entrenamiento

In [95]:
# Construcción de la red
model = build_classification_model(train_X)

# Entrenamiento
history = model.fit(train_X, train_Y, batch_size=32, epochs=1000, verbose=1)

Epoch 1/1000
335/335 [==============================] - 2s 6ms/sample - loss: 1.5431 - acc: 0.2776 - categorical_accuracy: 0.2776 - mean_squared_error: 0.1552
Epoch 2/1000
335/335 [==============================] - 0s 259us/sample - loss: 1.4473 - acc: 0.4000 - categorical_accuracy: 0.4000 - mean_squared_error: 0.1470
Epoch 3/1000
335/335 [==============================] - 0s 274us/sample - loss: 1.4102 - acc: 0.4000 - categorical_accuracy: 0.4000 - mean_squared_error: 0.1445
Epoch 4/1000
335/335 [==============================] - 0s 272us/sample - loss: 1.3822 - acc: 0.4000 - categorical_accuracy: 0.4000 - mean_squared_error: 0.1424
Epoch 5/1000
335/335 [==============================] - 0s 268us/sample - loss: 1.3507 - acc: 0.4269 - categorical_accuracy: 0.4269 - mean_squared_error: 0.1399
Epoch 6/1000
335/335 [==============================] - 0s 338us/sample - loss: 1.3166 - acc: 0.4478 - categorical_accuracy: 0.4478 - mean_squared_error: 0.1373
Epoch 7/1000
335/335 [==============

335/335 [==============================] - 0s 266us/sample - loss: 0.9708 - acc: 0.5761 - categorical_accuracy: 0.5761 - mean_squared_error: 0.1113
Epoch 52/1000
335/335 [==============================] - 0s 265us/sample - loss: 0.9703 - acc: 0.5642 - categorical_accuracy: 0.5642 - mean_squared_error: 0.1112
Epoch 53/1000
335/335 [==============================] - 0s 261us/sample - loss: 0.9768 - acc: 0.5612 - categorical_accuracy: 0.5612 - mean_squared_error: 0.1121
Epoch 54/1000
335/335 [==============================] - 0s 264us/sample - loss: 0.9678 - acc: 0.5701 - categorical_accuracy: 0.5701 - mean_squared_error: 0.1112
Epoch 55/1000
335/335 [==============================] - 0s 385us/sample - loss: 0.9670 - acc: 0.5761 - categorical_accuracy: 0.5761 - mean_squared_error: 0.1110
Epoch 56/1000
335/335 [==============================] - 0s 266us/sample - loss: 0.9670 - acc: 0.5701 - categorical_accuracy: 0.5701 - mean_squared_error: 0.1111
Epoch 57/1000
335/335 [===================

335/335 [==============================] - 0s 261us/sample - loss: 0.9296 - acc: 0.5940 - categorical_accuracy: 0.5940 - mean_squared_error: 0.1074
Epoch 102/1000
335/335 [==============================] - 0s 259us/sample - loss: 0.9351 - acc: 0.5881 - categorical_accuracy: 0.5881 - mean_squared_error: 0.1081
Epoch 103/1000
335/335 [==============================] - 0s 246us/sample - loss: 0.9324 - acc: 0.5881 - categorical_accuracy: 0.5881 - mean_squared_error: 0.1077
Epoch 104/1000
335/335 [==============================] - 0s 257us/sample - loss: 0.9402 - acc: 0.5672 - categorical_accuracy: 0.5672 - mean_squared_error: 0.1087
Epoch 105/1000
335/335 [==============================] - 0s 253us/sample - loss: 0.9302 - acc: 0.5881 - categorical_accuracy: 0.5881 - mean_squared_error: 0.1074
Epoch 106/1000
335/335 [==============================] - 0s 258us/sample - loss: 0.9361 - acc: 0.5940 - categorical_accuracy: 0.5940 - mean_squared_error: 0.1081
Epoch 107/1000
335/335 [=============

335/335 [==============================] - 0s 282us/sample - loss: 0.9017 - acc: 0.6090 - categorical_accuracy: 0.6090 - mean_squared_error: 0.1048
Epoch 151/1000
335/335 [==============================] - 0s 264us/sample - loss: 0.9016 - acc: 0.6030 - categorical_accuracy: 0.6030 - mean_squared_error: 0.1049
Epoch 152/1000
335/335 [==============================] - 0s 242us/sample - loss: 0.9037 - acc: 0.5881 - categorical_accuracy: 0.5881 - mean_squared_error: 0.1054
Epoch 153/1000
335/335 [==============================] - 0s 251us/sample - loss: 0.8993 - acc: 0.6090 - categorical_accuracy: 0.6090 - mean_squared_error: 0.1046
Epoch 154/1000
335/335 [==============================] - 0s 265us/sample - loss: 0.8978 - acc: 0.6000 - categorical_accuracy: 0.6000 - mean_squared_error: 0.1045
Epoch 155/1000
335/335 [==============================] - 0s 268us/sample - loss: 0.8973 - acc: 0.6030 - categorical_accuracy: 0.6030 - mean_squared_error: 0.1045
Epoch 156/1000
335/335 [=============

335/335 [==============================] - 0s 269us/sample - loss: 0.8731 - acc: 0.6119 - categorical_accuracy: 0.6119 - mean_squared_error: 0.1022
Epoch 201/1000
335/335 [==============================] - 0s 248us/sample - loss: 0.8703 - acc: 0.6090 - categorical_accuracy: 0.6090 - mean_squared_error: 0.1018
Epoch 202/1000
335/335 [==============================] - 0s 250us/sample - loss: 0.8696 - acc: 0.6060 - categorical_accuracy: 0.6060 - mean_squared_error: 0.1018
Epoch 203/1000
335/335 [==============================] - 0s 251us/sample - loss: 0.8628 - acc: 0.6239 - categorical_accuracy: 0.6239 - mean_squared_error: 0.1010
Epoch 204/1000
335/335 [==============================] - 0s 681us/sample - loss: 0.8597 - acc: 0.6119 - categorical_accuracy: 0.6119 - mean_squared_error: 0.1009
Epoch 205/1000
335/335 [==============================] - 0s 265us/sample - loss: 0.8625 - acc: 0.6209 - categorical_accuracy: 0.6209 - mean_squared_error: 0.1010
Epoch 206/1000
335/335 [=============

335/335 [==============================] - 0s 275us/sample - loss: 0.8212 - acc: 0.6418 - categorical_accuracy: 0.6418 - mean_squared_error: 0.0969
Epoch 251/1000
335/335 [==============================] - 0s 257us/sample - loss: 0.8186 - acc: 0.6209 - categorical_accuracy: 0.6209 - mean_squared_error: 0.0964
Epoch 252/1000
335/335 [==============================] - 0s 248us/sample - loss: 0.8259 - acc: 0.6299 - categorical_accuracy: 0.6299 - mean_squared_error: 0.0974
Epoch 253/1000
335/335 [==============================] - 0s 249us/sample - loss: 0.8188 - acc: 0.6328 - categorical_accuracy: 0.6328 - mean_squared_error: 0.0965
Epoch 254/1000
335/335 [==============================] - 0s 249us/sample - loss: 0.8466 - acc: 0.6299 - categorical_accuracy: 0.6299 - mean_squared_error: 0.0995
Epoch 255/1000
335/335 [==============================] - 0s 242us/sample - loss: 0.8276 - acc: 0.6239 - categorical_accuracy: 0.6239 - mean_squared_error: 0.0979
Epoch 256/1000
335/335 [=============

335/335 [==============================] - 0s 298us/sample - loss: 0.7745 - acc: 0.6657 - categorical_accuracy: 0.6657 - mean_squared_error: 0.0919
Epoch 301/1000
335/335 [==============================] - 0s 260us/sample - loss: 0.7706 - acc: 0.6507 - categorical_accuracy: 0.6507 - mean_squared_error: 0.0918
Epoch 302/1000
335/335 [==============================] - 0s 255us/sample - loss: 0.7742 - acc: 0.6567 - categorical_accuracy: 0.6567 - mean_squared_error: 0.0923
Epoch 303/1000
335/335 [==============================] - 0s 255us/sample - loss: 0.7683 - acc: 0.6597 - categorical_accuracy: 0.6597 - mean_squared_error: 0.0913
Epoch 304/1000
335/335 [==============================] - 0s 257us/sample - loss: 0.7641 - acc: 0.6627 - categorical_accuracy: 0.6627 - mean_squared_error: 0.0907
Epoch 305/1000
335/335 [==============================] - 0s 255us/sample - loss: 0.7753 - acc: 0.6478 - categorical_accuracy: 0.6478 - mean_squared_error: 0.0928
Epoch 306/1000
335/335 [=============

335/335 [==============================] - 0s 275us/sample - loss: 0.7227 - acc: 0.6657 - categorical_accuracy: 0.6657 - mean_squared_error: 0.0867
Epoch 351/1000
335/335 [==============================] - 0s 275us/sample - loss: 0.7225 - acc: 0.6776 - categorical_accuracy: 0.6776 - mean_squared_error: 0.0866
Epoch 352/1000
335/335 [==============================] - 0s 264us/sample - loss: 0.7184 - acc: 0.6896 - categorical_accuracy: 0.6896 - mean_squared_error: 0.0860
Epoch 353/1000
335/335 [==============================] - 0s 251us/sample - loss: 0.7236 - acc: 0.6776 - categorical_accuracy: 0.6776 - mean_squared_error: 0.0870
Epoch 354/1000
335/335 [==============================] - 0s 255us/sample - loss: 0.7256 - acc: 0.6776 - categorical_accuracy: 0.6776 - mean_squared_error: 0.0871
Epoch 355/1000
335/335 [==============================] - 0s 265us/sample - loss: 0.7535 - acc: 0.6687 - categorical_accuracy: 0.6687 - mean_squared_error: 0.0899
Epoch 356/1000
335/335 [=============

335/335 [==============================] - 0s 282us/sample - loss: 0.6913 - acc: 0.6925 - categorical_accuracy: 0.6925 - mean_squared_error: 0.0833
Epoch 400/1000
335/335 [==============================] - 0s 250us/sample - loss: 0.6861 - acc: 0.6925 - categorical_accuracy: 0.6925 - mean_squared_error: 0.0826
Epoch 401/1000
335/335 [==============================] - 0s 267us/sample - loss: 0.6914 - acc: 0.6896 - categorical_accuracy: 0.6896 - mean_squared_error: 0.0831
Epoch 402/1000
335/335 [==============================] - 0s 303us/sample - loss: 0.6932 - acc: 0.7075 - categorical_accuracy: 0.7075 - mean_squared_error: 0.0832
Epoch 403/1000
335/335 [==============================] - 0s 268us/sample - loss: 0.6902 - acc: 0.6866 - categorical_accuracy: 0.6866 - mean_squared_error: 0.0829
Epoch 404/1000
335/335 [==============================] - 0s 329us/sample - loss: 0.6817 - acc: 0.6836 - categorical_accuracy: 0.6836 - mean_squared_error: 0.0820
Epoch 405/1000
335/335 [=============

335/335 [==============================] - 0s 263us/sample - loss: 0.6814 - acc: 0.6746 - categorical_accuracy: 0.6746 - mean_squared_error: 0.0827
Epoch 450/1000
335/335 [==============================] - 0s 266us/sample - loss: 0.7132 - acc: 0.6806 - categorical_accuracy: 0.6806 - mean_squared_error: 0.0861
Epoch 451/1000
335/335 [==============================] - 0s 263us/sample - loss: 0.7144 - acc: 0.6746 - categorical_accuracy: 0.6746 - mean_squared_error: 0.0869
Epoch 452/1000
335/335 [==============================] - 0s 272us/sample - loss: 0.6813 - acc: 0.6896 - categorical_accuracy: 0.6896 - mean_squared_error: 0.0823
Epoch 453/1000
335/335 [==============================] - 0s 272us/sample - loss: 0.6645 - acc: 0.6925 - categorical_accuracy: 0.6925 - mean_squared_error: 0.0807
Epoch 454/1000
335/335 [==============================] - 0s 322us/sample - loss: 0.6849 - acc: 0.6925 - categorical_accuracy: 0.6925 - mean_squared_error: 0.0825
Epoch 455/1000
335/335 [=============

335/335 [==============================] - 0s 280us/sample - loss: 0.6396 - acc: 0.7284 - categorical_accuracy: 0.7284 - mean_squared_error: 0.0767
Epoch 500/1000
335/335 [==============================] - 0s 262us/sample - loss: 0.6449 - acc: 0.7015 - categorical_accuracy: 0.7015 - mean_squared_error: 0.0784
Epoch 501/1000
335/335 [==============================] - 0s 256us/sample - loss: 0.6311 - acc: 0.7284 - categorical_accuracy: 0.7284 - mean_squared_error: 0.0760
Epoch 502/1000
335/335 [==============================] - 0s 270us/sample - loss: 0.6567 - acc: 0.6985 - categorical_accuracy: 0.6985 - mean_squared_error: 0.0798
Epoch 503/1000
335/335 [==============================] - 0s 269us/sample - loss: 0.6491 - acc: 0.6806 - categorical_accuracy: 0.6806 - mean_squared_error: 0.0795
Epoch 504/1000
335/335 [==============================] - 0s 256us/sample - loss: 0.6648 - acc: 0.6955 - categorical_accuracy: 0.6955 - mean_squared_error: 0.0803
Epoch 505/1000
335/335 [=============

335/335 [==============================] - 0s 264us/sample - loss: 0.6697 - acc: 0.7015 - categorical_accuracy: 0.7015 - mean_squared_error: 0.0817
Epoch 550/1000
335/335 [==============================] - 0s 263us/sample - loss: 0.6447 - acc: 0.7075 - categorical_accuracy: 0.7075 - mean_squared_error: 0.0784
Epoch 551/1000
335/335 [==============================] - 0s 251us/sample - loss: 0.6327 - acc: 0.7134 - categorical_accuracy: 0.7134 - mean_squared_error: 0.0767
Epoch 552/1000
335/335 [==============================] - 0s 254us/sample - loss: 0.6200 - acc: 0.7164 - categorical_accuracy: 0.7164 - mean_squared_error: 0.0755
Epoch 553/1000
335/335 [==============================] - 0s 252us/sample - loss: 0.6669 - acc: 0.6985 - categorical_accuracy: 0.6985 - mean_squared_error: 0.0815
Epoch 554/1000
335/335 [==============================] - 0s 458us/sample - loss: 0.6348 - acc: 0.7164 - categorical_accuracy: 0.7164 - mean_squared_error: 0.0771
Epoch 555/1000
335/335 [=============

335/335 [==============================] - 0s 271us/sample - loss: 0.6182 - acc: 0.7164 - categorical_accuracy: 0.7164 - mean_squared_error: 0.0748
Epoch 600/1000
335/335 [==============================] - 0s 277us/sample - loss: 0.6152 - acc: 0.7343 - categorical_accuracy: 0.7343 - mean_squared_error: 0.0745
Epoch 601/1000
335/335 [==============================] - 0s 260us/sample - loss: 0.6364 - acc: 0.7164 - categorical_accuracy: 0.7164 - mean_squared_error: 0.0767
Epoch 602/1000
335/335 [==============================] - 0s 253us/sample - loss: 0.6317 - acc: 0.7224 - categorical_accuracy: 0.7224 - mean_squared_error: 0.0770
Epoch 603/1000
335/335 [==============================] - 0s 254us/sample - loss: 0.6290 - acc: 0.7104 - categorical_accuracy: 0.7104 - mean_squared_error: 0.0770
Epoch 604/1000
335/335 [==============================] - 0s 246us/sample - loss: 0.6244 - acc: 0.7284 - categorical_accuracy: 0.7284 - mean_squared_error: 0.0760
Epoch 605/1000
335/335 [=============

335/335 [==============================] - 0s 273us/sample - loss: 0.6074 - acc: 0.7194 - categorical_accuracy: 0.7194 - mean_squared_error: 0.0740
Epoch 650/1000
335/335 [==============================] - 0s 447us/sample - loss: 0.6034 - acc: 0.7403 - categorical_accuracy: 0.7403 - mean_squared_error: 0.0727
Epoch 651/1000
335/335 [==============================] - 0s 296us/sample - loss: 0.6018 - acc: 0.7284 - categorical_accuracy: 0.7284 - mean_squared_error: 0.0731
Epoch 652/1000
335/335 [==============================] - 0s 269us/sample - loss: 0.5986 - acc: 0.7522 - categorical_accuracy: 0.7522 - mean_squared_error: 0.0722
Epoch 653/1000
335/335 [==============================] - 0s 244us/sample - loss: 0.6250 - acc: 0.7075 - categorical_accuracy: 0.7075 - mean_squared_error: 0.0767
Epoch 654/1000
335/335 [==============================] - 0s 277us/sample - loss: 0.6100 - acc: 0.7403 - categorical_accuracy: 0.7403 - mean_squared_error: 0.0740
Epoch 655/1000
335/335 [=============

335/335 [==============================] - 0s 262us/sample - loss: 0.5895 - acc: 0.7343 - categorical_accuracy: 0.7343 - mean_squared_error: 0.0712
Epoch 700/1000
335/335 [==============================] - 0s 269us/sample - loss: 0.6053 - acc: 0.7254 - categorical_accuracy: 0.7254 - mean_squared_error: 0.0743
Epoch 701/1000
335/335 [==============================] - 0s 275us/sample - loss: 0.5876 - acc: 0.7612 - categorical_accuracy: 0.7612 - mean_squared_error: 0.0704
Epoch 702/1000
335/335 [==============================] - 0s 258us/sample - loss: 0.5866 - acc: 0.7254 - categorical_accuracy: 0.7254 - mean_squared_error: 0.0714
Epoch 703/1000
335/335 [==============================] - 0s 261us/sample - loss: 0.6178 - acc: 0.7164 - categorical_accuracy: 0.7164 - mean_squared_error: 0.0751
Epoch 704/1000
335/335 [==============================] - 0s 251us/sample - loss: 0.5856 - acc: 0.7522 - categorical_accuracy: 0.7522 - mean_squared_error: 0.0708
Epoch 705/1000
335/335 [=============

335/335 [==============================] - 0s 274us/sample - loss: 0.5766 - acc: 0.7433 - categorical_accuracy: 0.7433 - mean_squared_error: 0.0696
Epoch 750/1000
335/335 [==============================] - 0s 266us/sample - loss: 0.5852 - acc: 0.7433 - categorical_accuracy: 0.7433 - mean_squared_error: 0.0708
Epoch 751/1000
335/335 [==============================] - 0s 256us/sample - loss: 0.5795 - acc: 0.7403 - categorical_accuracy: 0.7403 - mean_squared_error: 0.0697
Epoch 752/1000
335/335 [==============================] - 0s 748us/sample - loss: 0.5730 - acc: 0.7284 - categorical_accuracy: 0.7284 - mean_squared_error: 0.0695
Epoch 753/1000
335/335 [==============================] - 0s 250us/sample - loss: 0.5803 - acc: 0.7493 - categorical_accuracy: 0.7493 - mean_squared_error: 0.0700
Epoch 754/1000
335/335 [==============================] - 0s 381us/sample - loss: 0.5799 - acc: 0.7373 - categorical_accuracy: 0.7373 - mean_squared_error: 0.0707
Epoch 755/1000
335/335 [=============

335/335 [==============================] - 0s 301us/sample - loss: 0.5833 - acc: 0.7284 - categorical_accuracy: 0.7284 - mean_squared_error: 0.0710
Epoch 800/1000
335/335 [==============================] - 0s 329us/sample - loss: 0.5722 - acc: 0.7612 - categorical_accuracy: 0.7612 - mean_squared_error: 0.0687
Epoch 801/1000
335/335 [==============================] - 0s 254us/sample - loss: 0.5755 - acc: 0.7433 - categorical_accuracy: 0.7433 - mean_squared_error: 0.0703
Epoch 802/1000
335/335 [==============================] - 0s 252us/sample - loss: 0.5713 - acc: 0.7612 - categorical_accuracy: 0.7612 - mean_squared_error: 0.0682
Epoch 803/1000
335/335 [==============================] - 0s 345us/sample - loss: 0.5732 - acc: 0.7493 - categorical_accuracy: 0.7493 - mean_squared_error: 0.0695
Epoch 804/1000
335/335 [==============================] - 0s 506us/sample - loss: 0.5760 - acc: 0.7313 - categorical_accuracy: 0.7313 - mean_squared_error: 0.0703
Epoch 805/1000
335/335 [=============

335/335 [==============================] - 0s 270us/sample - loss: 0.5628 - acc: 0.7463 - categorical_accuracy: 0.7463 - mean_squared_error: 0.0682
Epoch 850/1000
335/335 [==============================] - 0s 298us/sample - loss: 0.5646 - acc: 0.7552 - categorical_accuracy: 0.7552 - mean_squared_error: 0.0690
Epoch 851/1000
335/335 [==============================] - 0s 266us/sample - loss: 0.5669 - acc: 0.7373 - categorical_accuracy: 0.7373 - mean_squared_error: 0.0690
Epoch 852/1000
335/335 [==============================] - 0s 272us/sample - loss: 0.5745 - acc: 0.7284 - categorical_accuracy: 0.7284 - mean_squared_error: 0.0698
Epoch 853/1000
335/335 [==============================] - 0s 281us/sample - loss: 0.5707 - acc: 0.7463 - categorical_accuracy: 0.7463 - mean_squared_error: 0.0694
Epoch 854/1000
335/335 [==============================] - 0s 284us/sample - loss: 0.5817 - acc: 0.7284 - categorical_accuracy: 0.7284 - mean_squared_error: 0.0705
Epoch 855/1000
335/335 [=============

335/335 [==============================] - 0s 285us/sample - loss: 0.5650 - acc: 0.7493 - categorical_accuracy: 0.7493 - mean_squared_error: 0.0683
Epoch 900/1000
335/335 [==============================] - 0s 275us/sample - loss: 0.5526 - acc: 0.7672 - categorical_accuracy: 0.7672 - mean_squared_error: 0.0671
Epoch 901/1000
335/335 [==============================] - 0s 264us/sample - loss: 0.5498 - acc: 0.7552 - categorical_accuracy: 0.7552 - mean_squared_error: 0.0668
Epoch 902/1000
335/335 [==============================] - 0s 267us/sample - loss: 0.5974 - acc: 0.7403 - categorical_accuracy: 0.7403 - mean_squared_error: 0.0730
Epoch 903/1000
335/335 [==============================] - 0s 258us/sample - loss: 0.5891 - acc: 0.7731 - categorical_accuracy: 0.7731 - mean_squared_error: 0.0706
Epoch 904/1000
335/335 [==============================] - 0s 280us/sample - loss: 0.5542 - acc: 0.7493 - categorical_accuracy: 0.7493 - mean_squared_error: 0.0671
Epoch 905/1000
335/335 [=============

335/335 [==============================] - 0s 270us/sample - loss: 0.5536 - acc: 0.7701 - categorical_accuracy: 0.7701 - mean_squared_error: 0.0663
Epoch 950/1000
335/335 [==============================] - 0s 280us/sample - loss: 0.5530 - acc: 0.7463 - categorical_accuracy: 0.7463 - mean_squared_error: 0.0673
Epoch 951/1000
335/335 [==============================] - 0s 264us/sample - loss: 0.5935 - acc: 0.7373 - categorical_accuracy: 0.7373 - mean_squared_error: 0.0732
Epoch 952/1000
335/335 [==============================] - 0s 250us/sample - loss: 0.5886 - acc: 0.7254 - categorical_accuracy: 0.7254 - mean_squared_error: 0.0721
Epoch 953/1000
335/335 [==============================] - 0s 259us/sample - loss: 0.5742 - acc: 0.7522 - categorical_accuracy: 0.7522 - mean_squared_error: 0.0696
Epoch 954/1000
335/335 [==============================] - 0s 249us/sample - loss: 0.5680 - acc: 0.7552 - categorical_accuracy: 0.7552 - mean_squared_error: 0.0689
Epoch 955/1000
335/335 [=============

335/335 [==============================] - 0s 268us/sample - loss: 0.5945 - acc: 0.7284 - categorical_accuracy: 0.7284 - mean_squared_error: 0.0726
Epoch 1000/1000
335/335 [==============================] - 0s 307us/sample - loss: 0.5684 - acc: 0.7373 - categorical_accuracy: 0.7373 - mean_squared_error: 0.0687


### Casos de éxito

Se calculan los casos de éxito del modelo entrenado a partir de las predicciones sobre el set de validación

In [94]:
# Predicción
scores = model.evaluate(test_X, test_Y)
print("\nCasos de éxito: %.2f%%" % (scores[1]*100))

165/165 [==============================] - 0s 251us/sample - loss: 0.6923 - acc: 0.7212 - categorical_accuracy: 0.7212 - mean_squared_error: 0.0835

Casos de éxito: 72.12%
